version: '3'
services:
  client:
    build: .
    ports:
      - 3001:80

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=sheticonmytactilitoe.duckdns.org
      - VALIDATION=duckdns
      - STAGING=true
    volumes:
      - ./swag/config:/config
    ports:
      - 0.0.0.0:3001:80
    restart: unless-stopped