version: "3"
services:
  client:
    build: .
    # ports:
    # - 0.0.0.0:3011:80

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    env_file:
    - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=<duckdns domain here>
      - VALIDATION=duckdns
      - STAGING=false
    volumes:
      - /home/<your user here>/data/swag:/config
      - ./default.conf:/config/nginx/site-confs/default.conf # new part
    ports:
    - 0.0.0.0:3001:443 # note using port 443
    restart: unless-stopped